### ISSUE TITLE
Image randomly garbled

### ISSUE THREAD

**Issue by kiedtl** [lptstr/winfetch#8] opened 2019-04-08 16:11 UTC
![image](https://user-images.githubusercontent.com/32681240/55739651-75396280-59f7-11e9-88cb-bbe5e7966901.png)

This seems to occur when using winfetch like so:
```
$ clear; winfetch -image ~/winfetch-img.png
```
... but doesn't occur otherwise:

![image](https://user-images.githubusercontent.com/32681240/55739826-d9f4bd00-59f7-11e9-81bf-dbdf5941a9a7.png)

**Comment by JamesG269** [comment] 2019-04-22 19:17
Just wanted to add, that if you use strictmode version 5 or 6.2, your script has several problems pop up in vscode that may be relevant to this, such as:

```
Index was outside the bounds of the array.
At C:\Users\jgentile\Documents\PowerShell\winfetch.ps1:415 char:5
+     $logo_line = $img[$logoctr]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], IndexOutOfRangeException
    + FullyQualifiedErrorId : System.IndexOutOfRangeException
```

**Comment by kiedtl** [comment] 2019-04-22 22:57
> Just wanted to add, that if you use strictmode version 5 or 6.2, your script has several problems pop up in vscode that may be relevant to this, such as:
> 
> ```
> Index was outside the bounds of the array.
> At C:\Users\jgentile\Documents\PowerShell\winfetch.ps1:415 char:5
> +     $logo_line = $img[$logoctr]
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], IndexOutOfRangeException
>     + FullyQualifiedErrorId : System.IndexOutOfRangeException
> ```

mind creating a separate issue? Otherwise, thanks for reporting!

**Comment by JamesG269** [comment] 2019-04-22 23:58
I mean I can create a seperate issue, but I was debugging the garbled image and I thought this was the cause..

**Comment by kiedtl** [comment] 2019-04-23 13:46
> ```Index was outside the bounds of the array.
>  At C:\Users\jgentile\Documents\PowerShell\winfetch.ps1:415 char:5
>  +     $logo_line = $img[$logoctr]
>  +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      + CategoryInfo          : OperationStopped: (:) [], IndexOutOfRangeException
>      + FullyQualifiedErrorId : System.IndexOutOfRangeException
>  ```

I think this is caused because we programmatically add items to the array instead of hardcoding it. IMO this is not the cause.

**Comment by kiedtl** [comment] 2019-12-19 21:12
doesn't seem to be fixed :(

**Comment by jcwillox** [comment] 2021-02-04 04:57
This appears to be fixed with the new printing implementation, as we print the whole image at once, then go back to the top and print the info lines.

**Closed by jcwillox** 2021-02-04 04:57 UTC
Labels: bug, help wanted
