### ISSUE TITLE
Using image causes flickering display and freezes Windows

### ISSUE THREAD

**Issue by Phate6660** [lptstr/winfetch#18] opened 2019-12-17 13:12 UTC
Exactly as the title said. I was curious about it, so I decided to try `winfetch` with `-image` pointing to [this](https://vignette.wikia.nocookie.net/logopedia/images/0/08/Windows_%282001%29.svg/revision/latest/scale-to-width-down/175?cb=20170723123925) image. `winfetch` appears to freeze, then after a little bit Windows freezes, then my display starts flickering in and out. Until I get freaked out and quickly terminate `winfetch`.

**Comment by kiedtl** [comment] 2019-12-19 21:12
Possibly related to #8? I'm unable to figure out the cause of these image problems :(

**Comment by kiedtl** [comment] 2019-12-19 21:14
> then my display starts flickering in and out. Until I get freaked out and quickly terminate winfetch.

Your monitor or your terminal?

**Comment by Phate6660** [comment] 2019-12-19 21:22
My display. Everything freezes and flickers and even disconnects at some points.

**Comment by kiedtl** [comment] 2019-12-19 23:23
Really strange.

Can I have some system information? specifically:
- Make and model
- terminal
- Window version
- PowerShell version
- ImageMagick version

**Comment by Phate6660** [comment] 2019-12-20 05:56
> Make and model

Of?

> terminal

I've tried it in cmd, Fluent Terminal, and Windows' new terminal.

> Windows version

Windows 10 Pro | Version: 1903 | Build: 18362.30

> PowerShell version

Both 5.1.1 and 6.2.3.

> ImageMagick version

7.0.9-8 Q16 x64 2019-12-07

**Comment by kiedtl** [comment] 2019-12-20 20:59
I can't reproduce this :(

**Comment by rashil2000** [comment] 2021-02-04 12:46
Fixed in #48

**Closed by rashil2000** 2021-02-04 12:46 UTC
Labels: bug, help wanted
